### ISSUE TITLE
Enterprise network admin

### ISSUE THREAD

**Issue by becarpenter** [becarpenter/book6#18]
Chapter 1: add "How an enterprise network administrator sees IPv6" ?

[issue from Eduard Vasilenko]

**Comment by becarpenter** [comment]
Can we include that topic in "How a network operations center sees IPv6"?
(Personally I would like to abolish the job of "administrator", which is why I work on autonomic networking.)

**Comment by EduardVasilenko** [comment]
Enterprise, Carrier, and DC/Cloud NOCs are so different that it makes sense to have separate sections for them.

**Comment by buraglio** [comment]
I agree that there should be a perspective from Enterprise, Carrier, DC, NOC. We should be careful not to go too far down the hole as each of those can probably warrant its own book. Perhaps a common set of principles that is true across all deployments and then point out the divergence per discipline?

**Comment by becarpenter** [comment]
I agree, Nick, it would be best to have an overview, and then separate sub-sections where there are special aspects.
Remember, Chapter 1 with the section "How a network operations center sees IPv6" is intended to be general. We should put the more specific sections in 6 "Management and Operations" or even in 7 "Case studies". If people write text, we can decide where it fits best.

**Comment by becarpenter** [comment]
Have put some overview blurb in the Introduction/How a network operations center sees IPv6
The real content needs to go in the various chapters
