### ISSUE TITLE
Chapter 2 section headings

### ISSUE THREAD

**Issue by becarpenter** [becarpenter/book6#19]
Chapter 2:  Propose to change: "Layer 2 functions" to "Address resolution".
Propose to promote EH to an early position and demote DNS to the end of the section.

[Issue from Eduard Vasilenko]

**Comment by becarpenter** [comment]
I had assumed that "Layer 2 functions" would be about ipv6-over-foo.  But certainly ND has to be covered somewhere. Maybe an extra section is needed for that.
I am not too worried about the ordering of the sections. I hope the book can be read in any order!

**Comment by becarpenter** [comment]
I suggest keeping "Layer 2 functions" to cover exactly that: how IPv6 is transmitted (the Ethertype etc.). We need to add DHCPv6 somewhere (not blend it in with SLAAC). And we need to cover neighbor discovery too, which is another missing section.
Any other input? If not I will add to the section layout in a day or two.

**Comment by EduardVasilenko** [comment]
OK for me.

**Comment by becarpenter** [comment]
No further action
