### ISSUE TITLE
Chapter on economics?

### ISSUE THREAD

**Issue by becarpenter** [becarpenter/book6#23]
How about a chapter on the economics of IPv6 - because that's what gets the accountant's attention?
[Suggested by Ulrich Speidel]

**Comment by EduardVasilenko** [comment]
From one point of view, it is precious because it motivates people to do IPv6 adoption.
But from another point of view, it may be so disputable (if general) or specific to the particular situation.
IMHO: this mission is impossible.

**Comment by becarpenter** [comment]
I agree. If there is a reference for this we could point to it, but the tech community is probably not where we can find expertise.
So I'll close the issue for now.
