### ISSUE TITLE
Epub version?

### ISSUE THREAD

**Issue by symgryph** [becarpenter/book6#50]
I kind of wanted to read this on my ereader. Any interest in an EPUB verison of this?

**Comment by becarpenter** [comment]
I have no idea how much is needed to support an automatic markdown-to-EPUB conversion. The other unknown is whether we should stick to the github version of markdown or switch to something else (maybe more like what Wikipedia uses, for example).

That said, as long as we stick to the CC BY 4.0 license, I see no possible objection to EPUB. It's just a small matter of programming, as we used to say. Whoever does that programming gets to support it ;-).

**Comment by symgryph** [comment]
I might be able to hack together some scripts with pandoc. It won't be pretty but it might eventually work.

**Comment by becarpenter** [comment]
Let us know how that goes, and you could put the scripts in the 'utilities' folder at https://github.com/becarpenter/book6/tree/main/utilities

**Comment by slonopotamus** [comment]
There are [GitBook](https://www.gitbook.com/) and [mdBook](https://rust-lang.github.io/mdBook/) (and possibly others). They allow EPUB/PDF creation from Markdown files. But they expect that Markdown files follow some (not very complex) conventions.

**Comment by becarpenter** [comment]
Thanks. If we detect a strong demand for non-HTTPS access we can of course look into those. So far it seems to me that people seem happy with on-line access.

**Comment by becarpenter** [comment]
Could re-open but no real pressure for now
