### ISSUE TITLE
Suggestion: Reorder chapter 3 coexistence towards future (growing) options

### ISSUE THREAD

**Issue by sgryphon** [becarpenter/book6#51]
Reasoning: Want to engage the reader with new/growing technical direction, rather than legacy techniques (which they may already be familiar with). This is, for example, why you have "Obsolete techniques" towards the end (rather than beginning).

As was learnt with Winston Royce's 1970 paper on managing development, often people may skim the first section and say "let's do that", so make sure to put the best option forward first.

Specific suggestions:

(1) In the introduction, for the section at the end "To summarize the coexistence scenarios", reorder the bullet points in the following sequence:

* IPv6 only networks (a growing area), mentioning IPv4 as a service
* Dual stack, the current most common solution
* IPv4 only enclaves

(2) The sentence at the end does not mention dual stack, although it does say after IPv4 as a service is discontinued, IPv4 enclaves will be left by themselves (implying that dual stack was already discontinued). You could include an explicit mention, e.g.

"will be accessible by IPv6, in which case dual stack and then IPv4 as a service could be discontinued, leaving IPv4-only"

(3) Reorder the subsections within the chapter:

* Translation
* Dual stacks
* Tunnels
* IPv6 primary differences
* Obsolete techniques

This allows readers to simply skip the last section.

Some of this may be subjective, e.g. maybe the informative "IPv6 primary differences" should remain last, or even be first.

The main difference is the technology sections, putting Translation first, as it is the growing area that many readers will want to learn about, and likely the longest lived (as per the introduction, IPv4 as a service will likely remain after dual stack has disappeared).

I'm not sure where the IPv6-only considerations should sit, whether it was intended as part of translation, or a separate section. If a separate section I would put it first.

**Comment by becarpenter** [comment]
Afterthought: Perhaps the first section should be something like "Application and socket API view". That's where the dual stack concept will survive longest. Then the rest can clearly distinguish dual stack on the wire from the various IPv4aaS scenarios.

**Comment by sgryphon** [comment]
Hmm, I probably should have read the sections more in depth, rather than just skimming them. I see now that the section on "dual stack" spends very little time on dual-stack on the wire "ships in the night", and actually mostly talks about the translation mechanisms to provide the application/OS view of two stacks.

So, maybe it is the name as you suggest, i.e. while some applications will happily work in IPv6, there are some that will need to interface with IPv4 either because the software does not yet support IPv6 or because the destination is an IPv4 only server. 

There are then several approaches to providing applications with both IPv6 and IPv4 connectivity, either a translation mechanism where IPv4 is encapsulated in IPv6 (modern approach), a dual stack network (running both protocols on the write), or a tunnelling mechanisms where IPv6 is encapsulated in IPv4 (early approaches).

**Comment by becarpenter** [comment]
I've reworked the https://github.com/becarpenter/book6/tree/main/3.%20Coexistence%20with%20Legacy%20IPv4 chapter quite a bit in the last few days - please have a look. There are still more good points in the comments above.
I'd appreciate comments from @buraglio @netravnen @EduardVasilenko too.

**Comment by becarpenter** [comment]
Text seems stable for now
