### ISSUE TITLE
Suggestion: Chapter 3 section on dual stack (on the wire) could mention NAT64

### ISSUE THREAD

**Issue by sgryphon** [becarpenter/book6#52]
As part of the transition mechanism a dual stack (on the wire) network supports dual stack devices/clients communicating with both IPv4 and IPv6 (and dual stack) servers/hosts.

However a plain dual stack network does not allow an IPv6 only client to communicate with an IPv4 only server. An example might be a Thread device (IPv6 only) that wants to talk to a IPv4 only endpoint, although in that case the Thread protocol already covers what is needed.

In the more general case, this situation requires one of the translation mechanisms, such as NAT64 + DNS64, which will allow IPv6 only devices, on a dual stack network, to access IPv4 hosts, with no downside. (In contrast, without a similar mechanism, this combination would not be possible).

It does mean that dual stack clients will also use NAT64 (instead of NAT44) to access IPv4 only hosts, but they are using NAT either way.  (This is assume an IPv4 private network is used, which is the normal case).

I have a blog article that I posted (I had it in draft for a while, and posted it today) that I am happy to donate to the project, if you want to reuse any of the diagrams or text. (I just don't have time at the moment to re-write for the book). Only the first section is directly relevant, for running NAT64 + DNS64 in a dual stack (rather than IPv6 native) network.

Article is here: https://sgryphon.gamertheory.net/2022/12/14/running-nat64-in-a-dual-stack-network/

I also have the diagrams in ODG (LibreOffice Draw) and SVG format, which I can provide (the blog uses PNG).

**Comment by becarpenter** [comment]
Thanks much. I won't be doing much on this for the next couple of weeks for various reasons but will be back to it.

**Comment by becarpenter** [comment]
Updated Dual stack scenarios.md including a pointer to your blog. Thanks!
