### ISSUE TITLE
Need comments on multi-prefix text

### ISSUE THREAD

**Issue by becarpenter** [becarpenter/book6#55]
I'd like to invite comments on a new section I just added: https://github.com/becarpenter/book6/blob/main/6.%20Management%20and%20Operations/Multi-prefix%20operation.md . I'm sure it contains errors and has missing contents.

**Comment by buraglio** [comment]
Added some minor edits to my branch. Also created pull request for a few other changes in the topology hiding chapter.

**Comment by EduardVasilenko** [comment]
MHMP problem is very complex. The description is detailed but low on the scope.

In my taste, it is missing the discussion that could be 2 scenarios:
1. If an application uses bind() to attach itself to a particular source address then RFC8028 has a solution for choosing the proper next hop.
2. If an application uses getaddrinfo() that assumes next-hop choice first then rule 5/5.5 RFC 6724 advises on how to choose the source address compatible with the selected next hop.
The last case is more prevalent on hosts that need MHMP (MHMP is typically on the client side).

If you agree with the above - I could try to add text as a pull request.

In reality, much more could be added to the MHMP case (for example, the incapability to access a walled garden).
But I doubt where to stop on the case detalization.

There are 4 solutions for MHMP:
1. PI
2. PA
3. ULA+NPT
4. ULA+NAT
Should we discuss all 4? With all advantages and disadvantages that NAT has.

**Comment by becarpenter** [comment]
I suspect that there is also PA+NPT and PA+NAT, where you only translate for traffic to/from the backup ISP. But I feel strongly that we should only describe solutions that are deployable *today*.

(Is there more practical info about configuring source routing to make the multiple-PA work correctly? [The current text](https://github.com/becarpenter/book6/blob/main/6.%20Management%20and%20Operations/Multi-prefix%20operation.md) is rather vague.)

At the moment we only describe what is proposed in standards-track RFCs. I have a volunteer with direct experience to write some text on the NAT66/NPTv6 approaches - when that text arrives we can see how to integrate it.

**Comment by EduardVasilenko** [comment]
(Is there more practical info about configuring source routing to make the multiple-PA work correctly? [The current text](https://github.com/becarpenter/book6/blob/main/6.%20Management%20and%20Operations/Multi-prefix%20operation.md) is rather vague.)

IMHO: it does not make sense to discuss source routing
because there is no adopted mechanism in the industry to distribute PA prefixes dynamically over the site.
But if a reference is desired then it is probably RFC 8678 - it has a good discussion of what would be needed.

**Comment by becarpenter** [comment]
There is no suggestion of dynamic prefixes; we are talking about a classical situation with two (or more) static PA prefixes for an enterprise. (Possibly with an APAM tool that assigns longer prefixes to routers as needed.) There is no difficulty in principle about setting the necessary source routes in all routers, but as far as I know it has to be done by CLI commands and that is the operational complexity. 
For example, Juniper says: "we recommend that you use policy-based routing or filter-based forwarding to route packets based on source addresses." Cisco forum says "you need to use Policy Based Routing to achieve this". I believe it is the same for Huawei - configure a route policy including the source prefix. I will make this complexity more obvious in the text.
Agree that a reference to 8678 is needed. I'd forgotten that document.

**Comment by EduardVasilenko** [comment]
"Static PA prefix" does not make sense. It defeats multihoming in principle.
Multihoming is for resiliency as the primary goal. If the prefix could not be deprecated automatically (and fast enough) then no resiliency.
Then what was the value of multihoming?

I am not aware of any protocol that is adopted by the industry. HNCP was not adopted.

**Comment by becarpenter** [comment]
It's Happy Eyeballs techniques that provide session resiliency. That's why the failure of SHIM6 is a great pity, and why I think the TAPS work is very interesting. But I think that's still a v6ops/6man discussion. The operational reality *today* is that a broken ISP link will break most PA-based sessions, and the fix will be to start a new session. In book6 we want to describe today, not tomorrow.

**Comment by cron2** [comment]
Hi,

On Tue, Jan 10, 2023 at 12:57:35PM -0800, Brian E Carpenter wrote:
> It's Happy Eyeballs techniques that provide session resiliency. 

... but this is also something that never materialized, HE on the
source address level...

(Not even "unhappy eyeballs" as in "wait for a timeout and then retry
with a different source IP" has materialized)

So while I really really liked the idea of HNCP/homenet with dual PA
and automatic distribution / automatic router config for source-address
dependent routing, the market has decided to not want this on the router
side, and IETF has failed to provide guidance on the application stack
("source address HE").

Dead.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by EduardVasilenko** [comment]
> We don't deprecate the failing prefix in real-time, we redirect it. 

If the prefix is not deprecated then the host may use it.
Then it does not matter how many times we would redirect it (source routing of artificial intelligence) -> no exit for such the packet anyway.

I did not worry about all sessions dropping and restarting when the connection to the Carrier is lost - it is normal and looks inevitable.
Unfortunately, we have no mechanism yet to tell the host (especially behind the additional router hop) not to use the stale prefix.
Communication could not be re-established.
Hence, my claim that source routing is useless yet.
The mechanism to clean the stale PIOs for multi-hop is mandatory before the discussion for source routing.

**Comment by becarpenter** [comment]
@cron2 : Yes. I have no intention of mentioning HNCP in the book, wonderful though it might be in theory.

@EduardVasilenko : Yes, you are right but fixing these problems is IETF scope not book6 scope.

**Comment by becarpenter** [comment]
Nothing more to say until the IETF solves this!
