### ISSUE TITLE
About how many extension headers after basic headers.

### ISSUE THREAD

**Issue by verybigstrong** [becarpenter/book6#60]
2. IPv6 Basic Technology - Extension headers and options:"As explained in 2. Packet Format, every IPv6 packet includes _one or more extension headers_, of which the last one is the transport layer payload (UDP, TCP, etc.)."

RFC8200: "As illustrated in these examples, an IPv6 packet may carry _zero, one,  or more extension headers_, each identified by the Next Header field of the preceding header"

I think here should be "one or more additional headers" or " zero or more extension headers" ?

**Comment by becarpenter** [comment]
Yes, I will correct this, thanks, although the value of a packet with no extension headers escapes me :-).

**Comment by cron2** [comment]
Hi,

On Tue, Jan 10, 2023 at 11:44:32AM -0800, Brian E Carpenter wrote:
> Yes, I will correct this, thanks, although the value of a packet with no extension headers escapes me :-).

This really depends on whether you call a TCP or UDP header
"an extension header".  It's clearly a "next header", but is not
really an extension.

(IOW, all those things that make ISPs *drop* packets are EHs, not
the normal stuff :-) )

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by becarpenter** [comment]
Oops, I just updated my comment for that very reason. Never saw github comments cross in the post before!

**Comment by becarpenter** [comment]
I think the [updated text](https://github.com/becarpenter/book6/blob/main/2.%20IPv6%20Basic%20Technology/Extension%20headers%20and%20options.md) is correct: "every IPv6 packet may include one or more extension headers before the transport layer payload". I also added a note in [Packet Format](https://github.com/becarpenter/book6/blob/main/2.%20IPv6%20Basic%20Technology/Packet%20Format.md).
Closing the issue for now.
