### ISSUE TITLE
RFC bibliography

### ISSUE THREAD

**Issue by bobhinden** [becarpenter/book6#77]
Would it be useful to have a separate sublist of STDs?

Also, are there any IPv6 related RFCs that don't have "IPv6" in the title?

**Comment by becarpenter** [comment]
> Would it be useful to have a separate sublist of STDs?
There are only 3 (which is kind of a problem...)
> Also, are there any IPv6 related RFCs that don't have "IPv6" in the title?
Very possibly, but I would have to special case them. Any way to find them?

**Comment by bobhinden** [comment]
> > Would it be useful to have a separate sublist of STDs?
> 
> There are only 3 (which is kind of a problem...)

Good point, probably not worthwhile.

> 
> > Also, are there any IPv6 related RFCs that don't have "IPv6" in the title?
> 
> Very possibly, but I would have to special case them. Any way to find them?

I just looked at the RFC's produced by 6MAN and found:

Gratuitous Neighbor Discovery: Creating Neighbor Cache Entries on First-Hop Routers
ICMPv6 Errors for Discarding Packets Due to Processing Limits
Discovering PREF64 in Router Advertisements
Support for Adjustable Maximum Router Lifetimes per Link
Path MTU Discovery for IP version 6
First-Hop Router Selection by Hosts in a Multi-Prefix Network
Security Implications of Predictable Fragment Identification Values
Packet-Loss Resiliency for Router Solicitations
Enhanced Duplicate Address Detection
Neighbor Unreachability Detection Is Too Impatient
Distributing Address Selection Policy Using DHCPv6
Duplicate Address Detection Proxy
The Line-Identification Option
The Routing Protocol for Low-Power and Lossy Networks (RPL) Option for Carrying RPL Information in Data-Plane Datagrams

More than I thought.   Suggest that any RFC produced by 6MAN is probably IPv6 related.    That wouldn't have found RFC 6553.

**Comment by becarpenter** [comment]
Yes, I use the RFC Editor's XML index,  and it includes tags like <wg_acronym>6man</wg_acronym> so I can pick these up automatically. I can add this for 6man and v6ops with a few lines of code. Any other WGs to check?

**Comment by becarpenter** [comment]
Done. About 4 lines of Python to add all 6man and v6ops RFCs. Quite a collection: the log says "442 IPv6 RFCs found".

**Comment by bobhinden** [comment]
Cool!

Bob

**Comment by becarpenter** [comment]
I'm going to close the issue, but it would be easy to add other WG names to the dragnet.
