### ISSUE TITLE
Version number(s) for ST?

### ISSUE THREAD

**Issue by becarpenter** [becarpenter/book6#81]
In the nice new section [Why version 6](https://github.com/becarpenter/book6/blob/main/1.%20Introduction%20and%20Foreword/Why%20version%206.md) drafted by  @joaolucasmacedo (and copy-edited by me), it says:

> Number 7 was reserved for TP/IX [[RFC1475](https://www.rfc-editor.org/info/rfc1475)], as they expected ST version 2 would use number 6, which did not happen

Is that correct and if so, who was "they"? As far as I undertood it, all versions of ST were supposed to be version 5.

**Comment by joaolucasmacedo** [comment]
It is on session 2.2 of [RFC1475](https://www.rfc-editor.org/rfc/rfc1475.html#page-7). 
I knew I did read it somewhere but struggled to find.
So, "they" is RFC1475's author, R. Ullman.
If you find it a unnecessary piece to be on this article, please kindly remove.
Thanks for your review Brian.

**Comment by becarpenter** [comment]
Fixed (also corrected: the Kobe meeting was INET, not IETF)
