### ISSUE TITLE
Address planning: shorter or longer prefixes for subscribers?

### ISSUE THREAD

**Issue by bannmann** [becarpenter/book6#95]
Having just discovered this great book, I was idly skimming a few chapters when I stumbled over something that confused me, in `5. Network Design/Address Planning.md` (**_emphasis_** mine):

> ## Address Planning
> 
> As you would expect, in IPv6 networks all nodes may have globally unique
addresses. **_All networks will be given at least a /64 global prefix to
operate. As for carriers, they should deliver a longer prefix to
subscribers, so that they can have multiple /64 subnets within their
organizations or home environments._** Even a home customer can have a
public network prefix to be split into smaller networks, which is a
paradigm shift from “hiding behind NAT" on a few public IPv4 addresses
(or even inside `100.64.0.0/10`
\[[RFC6598](https://www.rfc-editor.org/info/rfc6598)\]).

I'm confused by the "should deliver a longer prefix to subscribers" part. It sounds like it's advocating e.g. a prefix length of e.g. /72, which would make IIDs smaller than 64 bits. Am I reading this wrong?

Come to think of it, the question maybe comes down to whom the "they" in "**_they_** can have multiple /64 subnets within their
organizations or home environments" refers to. If that's the subscribers, the carriers should really give them a prefix that is _shorter_ than /64, but _longer_ than the prefix the carrier itself is operating, right?

Either way, I suggest that sentence is rephrased to avoid potential ambiguities around the meaning of "they".

Disclaimer: I have only basic knowledge about IPv6 and am not a native speaker.

**Comment by becarpenter** [comment]
> I'm confused by the "should deliver a longer prefix to subscribers" part.

No wonder. It's wrong! It should be "shorter".

(I think everybody suffers from occasional confusion because a _bigger_ prefix means a _smaller_ address space, but we naturally associate _bigger_ with _longer_.)

You are also correct that the use of "they" is confusing. I'll fix the sentence, directly on the main branch. Thank you very much!

**Comment by becarpenter** [comment]
Fixed text with https://github.com/becarpenter/book6/commit/7c22b676444c30130b85aff4476d3c704e5f72a1
